### ISSUE TITLE
DHS Discontinuation rate 

### ISSUE THREAD

**Issue by Chauhan78** [DHSProgram/DHS-Indicators-Stata#12]
Hello, I am working on Discontinuation rate for India and running the whole code provided by DHS. While running the code I am getting the error variable V4 not found. Please help regrading this.

**Comment by dkale23** [comment]
Dear Mr. Chauhan,
The code needs to be modified as per the country. You need to check datasets for this and need to modify code as per the the variable.

**Comment by shireen122** [comment]
Hello, if you have any further question on this please post it on the DHS user forum GitHub thread here: https://userforum.dhsprogram.com/index.php?t=thread&frm_id=96& 

Thank you.
