### ISSUE TITLE
underweight status as per the child's living arrangements

### ISSUE THREAD

**Issue by MSahu40** [DHSProgram/DHS-Indicators-Stata#14]
Hello, I want to calculate the underweight status as per the child's living arrangements. can anyone please help me to match this with the DHS-India report
gen Child_liv_arr=.
replace Child_liv_arr=1 if hv111==1 & hv113==1 & (hv102 == 1 & hv105 < 18)
replace Child_liv_arr=2 if hv111==1 & hv113==0 & (hv102 == 1 & hv105 < 18)
replace Child_liv_arr=3 if hv111==0 & hv113==1 & (hv102 == 1 & hv105 < 18)
replace Child_liv_arr=4 if hv111==0 & hv113==0 & (hv102 == 0 & hv105 < 18)

label define Child_liv_arr 1"Living both Parents" 2"Living with Mother (not father)" 3"Living with Father (not mother)" 4"Living with neither parent", replace
label values Child_liv_arr Child_liv_arr
tab Child_liv_arr underweight [iw=wt], r nof

**Comment by MSahu40** [comment]
Hello, I want to calculate the underweight status as per the child's living arrangements. can anyone please help me to match this with the DHS-India report 
gen Child_liv_arr=.
replace Child_liv_arr=1 if hv111==1 & hv113==1 & (hv102 == 1  & hv105 < 18)
replace Child_liv_arr=2 if hv111==1 & hv113==0 & (hv102 == 1  & hv105 < 18)
replace Child_liv_arr=3 if hv111==0 & hv113==1 & (hv102 == 1  & hv105 < 18)
replace Child_liv_arr=4 if hv111!=1 & hv113!=1 & (hv102 == 1  & hv105 < 18)

label define Child_liv_arr 1"Living both Parents" 2"Living with Mother (not father)" 3"Living with Father (not mother)" 4"Living with neither parent", replace
label values Child_liv_arr Child_liv_arr
tab Child_liv_arr underweight [iw=wt], r nof

**Comment by shireen122** [comment]
Hello,

Please post your question on the DHS Program user forum website: https://userforum.dhsprogram.com/

Thank you.
