### ISSUE TITLE
Stillbirth, abortion, live births and Miscarriage - Error in code

### ISSUE THREAD

**Issue by pankhuri-jain** [DHSProgram/DHS-Indicators-Stata#15]
Following the code generated under chapter 08_CM (PMR), there is an error at _c__lonevar cmc = b3_

It presents as an ambiguous code; please provide guidance on resolving this.
![image](https://github.com/DHSProgram/DHS-Indicators-Stata/assets/81557557/7115373d-4f97-4729-a208-acf91282843d)

**Comment by shireen122** [comment]
Hello,
What is the error you are getting? I don't receive an error when I run `clonevar cmc=b3` using a BR data file. 

Thank you

**Comment by pankhuri-jain** [comment]
Dear Shireen,

Thank you for your reply.

I was able to resolve the error. However, I request you to please provide
guidance on how to modify the code to compute 'abortion' separately; since
miscarriage and abortion are a combined variable.

Thank you and best regards,
Pankhuri Jain

**Comment by pankhuri-jain** [comment]
Dear Shireen,

Looking forward to your response on guidance towards disaggregating the data separately for 'miscarriage' and 'abortion'. 

Thank you and best regards,
Pankhuri Jain

**Comment by shireen122** [comment]
Hello, 
In most surveys, you cannot differentiate between a miscarriage and an abortion. As you can see in the code these were both defined as "T" in the calendar data. However, if the survey you are working on does make this distinction in the final report then it would be possible. If so, please post your question on the DHS user form GitHub thread here: https://userforum.dhsprogram.com/index.php?t=thread&frm_id=96&

Please identify which survey you are using including the year and what table if any you are trying to match in the final report. Please also describe which do file you are working with from the repository.

Thank you.

**Comment by pankhuri-jain** [comment]
Dear Shireen,

Thank you for your guidance.

Regards,
Pankhuri
