### ISSUE TITLE
issues to estimate the percentage  of PNC utlization within 48 hrs using PDHS

### ISSUE THREAD

**Issue by margubur** [DHSProgram/DHS-Indicators-Stata#16]
I am using PDHS to calculate PNC within 48 hours using KR file of PDHS. Several times I tried to calculate it but failed to match it with the PDHS report. Could anyone provide me with the syntax of PNC?

**Comment by shireen122** [comment]
Hello,
Thank you for your question. Please post any questions on the calculation of indicator in the DHS user forum GitHub thread here: https://userforum.dhsprogram.com/index.php?t=thread&frm_id=96& 

In your post please specify the survey including the year, and the table you are trying to match. 

We will try to answer your question as soon as possible.

Thank you.
