### ISSUE TITLE
Error: Step 6--Output results in various ways for contraceptive discontinuation rates

### ISSUE THREAD

**Issue by awazir** [DHSProgram/DHS-Indicators-Stata#3]
Dear Programmers
This forum is really helpful and provided great help. Many Many thanks for this open-source platform. 

I have two questions regarding Contraceptive Discontinuation Rates. 
1. When I have run the step 6 of the discontinuation rate, 

line 394   putexcel B3:J`row', nformat(number_d2)
line 395 	putexcel K3:L`row', nformat(number)

         putexcel B3:J`row', nformat(number_d2)
option nformat() not allowed
r(198);

Please help me on how to handle this. 

2). I also want to calculate the discontinuation rates by background characteristics, such as subnational level, education or wealth status. 
I have tried a very simple way as to:
keep if v101==1, for subnational level
keep if v106==1, for no education, etc. 

Is there any systematic way to calculate rates by showing al labels at once. 

Thank you, Asi

**Comment by Guerillero** [comment]
What version of Stata are you running, @awazir?

**Comment by awazir** [comment]
STATA version 13.1
