### ISSUE TITLE
Can Previous pregnancy interval (in months) disaggregate by Stillbirths?

### ISSUE THREAD

**Issue by rishabhguptabhu** [DHSProgram/DHS-Indicators-Stata#6]
I have tried many times to compute previous pregnancy interval so that i may link with stillbirths (Table no: 7.5 {NFHS-4 National report}).
Please tell me how to create previous pregnancy interval?
@shireen122 @DHSProgram @courtneykirsten

**Comment by shireen122** [comment]
This question was answered on the DHS user forum here: https://userforum.dhsprogram.com/index.php?t=msg&goto=20219&#msg_20219

We also plan to update the CM_PMR.do file in Chapter 8 to include this background variable. 
Thank you.
