### ISSUE TITLE
DHS Code for merging GPS and survey data

### ISSUE THREAD

**Issue by sabrinakue** [DHSProgram/DHS-Indicators-Stata#7]
Hello everyone, 

does someone know where I could find a R or Stata code (or maybe any other guideline with e.g. QGIS) that gives me direction on how to merge the GPS data with the individual survey data?

thank you.

**Comment by Guerillero** [comment]
@sabrinakue Here is some stata code to do this join

https://gist.github.com/Guerillero/a3002a7e492a3042aba58662ce27e2ed
